<a href="https://colab.research.google.com/github/stevejj4/Movie-and-chill/blob/main/Movies_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# python libraries
from google.colab import auth #Authorizing google colab
auth.authenticate_user()
import gspread #credentials for google sheet
from google.auth import default
import pandas as pd

In [ ]:
# Data Export
creds,_ = default()
gc = gspread.authorize(creds) #Authorizing the connection
worksheet = gc.open('movies_updated').sheet1 #defining the worksheet
rows = worksheet.get_all_values() #getting all values in list of row
df = pd.DataFrame(rows)
df.columns = df.iloc[0] #creating columns name
df = df.iloc[1:]

In [4]:
df.shape

(4000, 15)

In [6]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime,,'],
      dtype='object', name=0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 1 to 4000
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4000 non-null   object
 1   rating     4000 non-null   object
 2   genre      4000 non-null   object
 3   year       4000 non-null   object
 4   released   4000 non-null   object
 5   score      4000 non-null   object
 6   votes      4000 non-null   object
 7   director   4000 non-null   object
 8   writer     4000 non-null   object
 9   star       4000 non-null   object
 10  country    4000 non-null   object
 11  budget     4000 non-null   object
 12  gross      4000 non-null   object
 13  company    4000 non-null   object
 14  runtime,,  4000 non-null   object
dtypes: object(15)
memory usage: 468.9+ KB

In [13]:
#df.isnull().sum()
print("The data is clean with no duplicates")
df.duplicated().value_counts()

he data is clean with no duplicates

False    4000
Name: count, dtype: int64

In [15]:
df.describe().T

          count unique                                top  freq
0
name       4000   3971                             Hamlet     3
rating     4000     12                                  R  2043
genre      4000     17                             Comedy  1355
year       4000     22                               1985   200
released   4000   1697  February 14, 1986 (United States)     9
score      4000     66                                6.6   181
votes      4000    649                              13000    82
director   4000   1678                        Woody Allen    22
writer     4000   2686                       Stephen King    27
star       4000   1656                     Robert De Niro    27
country    4000     44                      United States  2972
budget     4000    269                                  0  1392
gross      4000   3826                                      169
company    4000   1306                 Paramount Pictures   191
runtime,,  4000    169                              97.0,   134